USE [GEDMAF]
GO

select c.COLUMN_NAME, '[' + c.COLUMN_NAME + ']'
from INFORMATION_SCHEMA.COLUMNS c
where c.TABLE_CATALOG = 'GEDMAF'
and c.TABLE_SCHEMA = 'dbo'
and c.TABLE_NAME = 'V_AFFAIRE_PAPS'
order by c.COLUMN_NAME